# Generated by Django 4.2.6 on 2023-10-22 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="designation",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Admin"),
                    (2, "Weigher"),
                    (3, "Biller"),
                    (4, "Not Assigned"),
                ],
                default=4,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="place",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"type__in": [1, 3]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="organizations.place",
            ),
        ),
    ]
