# Generated by Django 4.2.6 on 2023-10-22 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0001_initial"),
        ("logistics", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="place",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"type__in": [1, 3]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stocks",
                to="organizations.place",
            ),
        ),
    ]
