# Generated by Django 4.2.6 on 2023-11-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "logistics",
            "0005_bill_is_active_billitem_is_active_record_record_type_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
