# Generated by Django 4.2.6 on 2023-11-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logistics", "0006_bill_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billitem",
            name="weight_unit",
            field=models.CharField(
                choices=[
                    ("kg", "Kilograms"),
                    ("g", "Grams"),
                    ("lb", "Pounds"),
                    ("t", "Tonne"),
                    ("kt", "KiloTonne"),
                ],
                default="kg",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="weight_unit",
            field=models.CharField(
                choices=[
                    ("kg", "Kilograms"),
                    ("g", "Grams"),
                    ("lb", "Pounds"),
                    ("t", "Tonne"),
                    ("kt", "KiloTonne"),
                ],
                default="kg",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="weight_unit",
            field=models.CharField(
                choices=[
                    ("kg", "Kilograms"),
                    ("g", "Grams"),
                    ("lb", "Pounds"),
                    ("t", "Tonne"),
                    ("kt", "KiloTonne"),
                ],
                default="kg",
                max_length=2,
            ),
        ),
    ]
