# Generated by Django 4.2.6 on 2024-02-20 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("fish", "0003_alter_fishvariant_weight_unit"),
        (
            "logistics",
            "0007_alter_billitem_weight_unit_alter_record_weight_unit_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="billitem",
            name="fish",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bill_items",
                to="fish.fish",
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="fish",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="records",
                to="fish.fish",
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="fish",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stocks",
                to="fish.fish",
            ),
        ),
    ]
