# Generated by Django 4.2.6 on 2024-02-28 04:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logistics", "0008_billitem_fish_record_fish_stock_fish"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="expense_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bill",
            name="pay_type",
            field=models.IntegerField(choices=[(1, "Cash"), (2, "GPay")], default=1),
        ),
    ]
