# Generated by Django 4.2.6 on 2024-02-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logistics", "0009_expense_expense_date_alter_bill_pay_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
