--\set DB_NAME `echo "$DB_NAME"`
--\set DB_USER `echo "$DB_USER"`
--\set DB_PASSWORD `echo "$DB_PASSWORD"`
--CREATE USER :DB_USER WITH PASSWORD :'DB_PASSWORD';
--CREATE DATABASE :DB_NAME;
--GRANT ALL PRIVILEGES ON DATABASE :DB_NAME TO :DB_USER;
--ALTER ROLE :DB_USER CREATEDB;

CREATE DATABASE farms;
CREATE USER dev WITH PASSWORD '123';
GRANT ALL PRIVILEGES ON DATABASE farms TO dev;
